### ISSUE TITLE
RHEL/CentOS 8.3 released

### ISSUE THREAD

**Issue by MikaelSmith** [replicatedhq/kURL#977]
https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/8.3_release_notes/overview

**Comment by MikaelSmith** [comment]
I get
```
error: git-2.27.0-1.el8.x86_64: erase failed
error: perl-IO-Socket-SSL-2.066-4.module_el8.3.0+410+ff426aa3.noarch: erase failed
error: git-core-doc-2.27.0-1.el8.noarch: erase failed
error: iptables-ebtables-1.8.4-15.el8.x86_64: erase failed
error: perl-Git-2.27.0-1.el8.noarch: erase failed
error: perl-Mozilla-CA-20160104-7.module_el8.3.0+416+dee7bcef.noarch: erase failed
error: git-core-2.27.0-1.el8.x86_64: erase failed
error: openssh-clients-8.0p1-5.el8.x86_64: erase failed
error: openssh-8.0p1-5.el8.x86_64: erase failed
error: iptables-1.8.4-15.el8.x86_64: erase failed
error: openssl-1:1.1.1g-11.el8.x86_64: erase failed
error: perl-Net-SSLeay-1.88-1.module_el8.3.0+410+ff426aa3.x86_64: erase failed
error: libnetfilter_queue-1.0.4-3.el8.x86_64: erase failed
main: line 1115: 302835 Segmentation fault      (core dumped) rpm --upgrade --force --nodeps $DIR/packages/kubernetes/${k8sVersion}/rhel-8/*.rpm
```
when I bypass the release version check. Trying the failing command directly
```
$ sudo rpm --upgrade --nodeps packages/kubernetes/1.17.13/rhel-8/*.rpm
warning: rpmdb: BDB2053 Freeing read locks for locker 0x312: 302835/140633933252480
warning: rpmdb: BDB2053 Freeing read locks for locker 0x313: 302835/140633933252480
warning: rpmdb: BDB2053 Freeing read locks for locker 0x314: 302835/140633933252480
warning: rpmdb: BDB2053 Freeing read locks for locker 0x315: 302835/140633933252480
warning: rpmdb: BDB2053 Freeing read locks for locker 0x316: 302835/140633933252480
warning: rpmdb: BDB2053 Freeing read locks for locker 0x317: 302835/140633933252480
warning: rpmdb: BDB2053 Freeing read locks for locker 0x318: 302835/140633933252480
warning: rpmdb: BDB2053 Freeing read locks for locker 0x319: 302835/140633933252480
warning: rpmdb: BDB2053 Freeing read locks for locker 0x31a: 302835/140633933252480
warning: rpmdb: BDB2053 Freeing read locks for locker 0x31b: 302835/140633933252480
warning: rpmdb: BDB2053 Freeing read locks for locker 0x31c: 302835/140633933252480
warning: rpmdb: BDB2053 Freeing read locks for locker 0x31d: 302835/140633933252480
warning: rpmdb: BDB2053 Freeing read locks for locker 0x30a: 302835/140633933252480
warning: rpmdb: BDB2053 Freeing read locks for locker 0x30c: 302835/140633933252480
warning: rpmdb: BDB2053 Freeing read locks for locker 0x30d: 302835/140633933252480
warning: rpmdb: BDB2053 Freeing read locks for locker 0x30e: 302835/140633933252480
warning: rpmdb: BDB2053 Freeing read locks for locker 0x30f: 302835/140633933252480
warning: rpmdb: BDB2053 Freeing read locks for locker 0x310: 302835/140633933252480
warning: rpmdb: BDB2053 Freeing read locks for locker 0x311: 302835/140633933252480
warning: packages/kubernetes/1.17.13/rhel-8/14bfe6e75a9efc8eca3f638eb22c7e2ce759c67f95b43b16fae4ebabde1549f3-cri-tools-1.13.0-0.x86_64.rpm: Header V4 RSA/SHA512 Signature, key ID 3e1ba8d5: NOKEY
Segmentation fault
```

**Comment by areed** [comment]
I'm not able to reproduce this error on CentOS or RHEL 8.3. It's possible this was resolved by the weekly rebuild of the packages containing the RPMs.

**Comment by MikaelSmith** [comment]
I'll give it another try then.

**Comment by MikaelSmith** [comment]
I'm upgrading on an instance that started as 8.1 or 8.2 and was upgraded to 8.3. Trying to run the upgrade script (online install) still fails. I didn't clean up any of the old packages, so I'll try deleting all the prior install files and re-running.

**Comment by MikaelSmith** [comment]
Update seems to be working after I cleared out all the prior install files.

**Comment by MikaelSmith** [comment]
New install is also good. So seems like just a problem from leaving the old versions of packages around rather than re-downloading them. Not sure if you want to try and fix or document something about that.

**Comment by areed** [comment]
We're treating this as a bug.

**Comment by tamarahenson** [comment]
Update:  Internal request #29816 regarding this issue has been resolved.
